### ISSUE TITLE
Bug with badge

### ISSUE THREAD

**Issue by TomasRoj** [dominiksalvet/gitpack#1]
**Environment**
Ubuntu 18.04 WSL

**Describe the bug**
When added the gitpack badge to readme bug happened. In front of displaying Git and [gitpack_test](https://github.com/TomasRoj/gitpack_test) (my test repo), it only displays git and Pack. Problably problem with underscore.

**Comment by dominiksalvet** [comment]
Well, this is how it should look like:

[![GitPack](https://img.shields.io/badge/Git-Pack-571997.svg)](https://github.com/dominiksalvet/gitpack)

So basically the badge itself has the text "Git Pack" although the project name is GitPack,

> It's not a bug, it's a feature.

@TomasRoj PS: I have edited your comment to contain a link to the project you were mentioning.

If it is OK, feel free to close the issue.

**Comment by dominiksalvet** [comment]
@TomasRoj After some consideration, I have simplified the badge and now it looks like this:

[![GitPack](https://img.shields.io/badge/-GitPack-571997)](https://github.com/dominiksalvet/gitpack)

The main reason behind that is the simplification itself. Also, your confusion (which makes sense) has certainly helped me to ultimately decide. Are you satisfied with the new badge? :smile:

**Comment by dominiksalvet** [comment]
@TomasRoj I am closing this issue as solved. If you have any additional comments, feel free to let me know. Thank you for contribution! :tada:
