### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by equillar** [dominiksalvet/gitpack#12]
**Environment**
Ubuntu 20.04

**Description**
Cant install gitpack

**Replication**
When Run on console  `wget -qO- https://raw.githubusercontent.com/dominiksalvet/gitpack/master/.install/initg.sh | sh`  i get: `installing GitPack globally
sh: 17: git: not found`

**Comment by dominiksalvet** [comment]
Hello, you need to install Git first. Try `sudo apt install git` and repeat.
