### ISSUE TITLE
Add troubleshooting guide

### ISSUE THREAD

**Issue by TomasRoj** [dominiksalvet/gitpack#2]
I would add .md file with basic troubleshooting.

**Comment by dominiksalvet** [comment]
Currently there is no need for a troubleshooting guide.

**Comment by dominiksalvet** [comment]
After some work on GitPack, that so called troubleshooting guide is indeed present now. :tada: It can be reached from the [*support.md*](https://github.com/dominiksalvet/gitpack/blob/master/support.md) file. Thank you @TomasRoj for all your help! :heart: 

> Note that it currently links to an [almost empty wiki](https://github.com/dominiksalvet/gitpack/wiki) but that will change one day. :next_track_button:
