### ISSUE TITLE
Should the GitPack installation be silent?

### ISSUE THREAD

**Issue by dominiksalvet** [dominiksalvet/gitpack#6]
**What is your question?**
What do you think about the GitPack's installation as stated in [the Install section](https://github.com/dominiksalvet/gitpack#install) of *README.dm* file? Should Git clone and checkout be silent/quiet not to confuse you, or is it ok as it is?

I would like to hear your opinions! :rocket: Thank you! :heart:

**Comment by purplecandy** [comment]
I'll vote for silent unless there are going to be multiple branches in production

**Comment by dominiksalvet** [comment]
@purplecandy Thank you for your opinion. :heart: I guess I will leave this issue open at least [until I get to GitPack again](https://github.com/users/dominiksalvet/projects/2). That should provide a lot of space for others as well. :rocket:
